function [Mid,Did,Dva] = ISLAB_5C(A,B,C,nk,N,sigma,lambda) 
%
% ISLAB_4A   Module that estimates an ARX model by using LSM. 
%
% Inputs:	A      # true coefficients of AR part 
%                        ([1 -1.5 0.7], by default)
%        	B      # true coefficients of X part 
%                        ([1 0.5], by default)
%        	C      # true coefficients of MA part (noise filter)
%                        ([1 -1 0.2], by default)
%               nk     # intrinsic delay of process (1, by default)
%               N      # simulation period (250, by default)
%               sigma  # standard deviation of PRB input 
%                        (1, by default); 
%                        if null, ARMA or AR processes are considered
%               lambda # standard deviation of white noise 
%                        (1, by default)
%
% Outputs:      Mid    # IDMODEL object representing the 
%                        estimated model
%               Did    # IDDATA object representing the 
%                        data generated for identification
%               Dva    # IDDATA object representing the 
%                        data generated for validation
%
% Explanation:	Data generated by an ARMAX process are employed 
%               to identify an ARX model with the help of 
%               Least Squares Method. The estimation is 
%               consistent, but not the most efficient 
%               (i.e. the convergence speed is not the best). 
%
% Author:   Dan Stefanoiu (*)
% Revised:  Dan Stefanoiu (*)
%
% Created: March 16, 2004
% Revised: January 22, 2012
%
% Copyright: (*) "Politehnica" Unversity of Bucharest, ROMANIA
%                Department of Automatic Control & Computer Science
%

%
% BEGIN
% 

global FIG ;			% Figure number handler 
FIG = 1;             

%
% Constants
% ~~~~~~~~~
alpha = 3 ;			% Weighting factor of 
				% confidence disks radius. 
pf = 1 ; 			% Plot flag: 0=no, 1=yes. 
Na = 8 ; 			% Maximum index of AR part. 
Nb = 8 ;			% Maximum index of X part. 
% 
% Faults preventing
% ~~~~~~~~~~~~~~~~~
if (nargin < 7)
   lambda = 1 ;
end 
if (isempty(lambda))
   lambda = 1 ;
end  
lambda = abs(lambda(1)) ; 
if (~lambda)
   lambda = 1 ; 
end  
if (nargin < 6)
   sigma = 1 ;
end  
if (isempty(sigma))
   sigma = 1 ;
end  
sigma = abs(sigma(1)) ; 
if (nargin < 5)
   N = 250 ;
end 
if (isempty(N))
   N = 250 ;
end  
N = abs(fix(N(1))) ; 
if (~N)
   N = 250 ;
end  
if (nargin < 4)
   nk = 1 ;
end 
if (isempty(nk))
   nk = 1 ;
end 
nk = abs(fix(nk(1))) ; 
if (~nk)
   nk = 1 ;
end  
if (nargin < 3)
   C = [1 -1 0.2] ;
end 
if (isempty(C))
   C = [1 -1 0.2] ;
end  
if (nargin < 2)
   B = [1 0.5] ;
end 
if (isempty(B))
   B = [1 0.5] ;
end  
if (nargin < 1)
   A = [1 -1.5 0.7] ;
end
if (isempty(A))
   A = [1 -1.5 0.7] ;
end

disp('Insert 0 for LSM solution')
disp('Insert 1 for IVM solution');
s_type = input('Solver type - ');
if s_type == 0
    [Mid,Did,Dva] = ISLAB_5A(A,B,C,nk,N,sigma,lambda); 
end
if s_type == 1
    disp('Insert 0 for IVM unfiltered');
    disp('Insert 1 for IVM first part filtered');
    disp('Insert 2 for IVM second part filtered');
    disp('Insert 3 for IVM filtered');
    filt = input('Solver type - ');
    [Mid,Did,Dva] = ISLAB_5D(A,B,C,nk,N,sigma,lambda, filt); 
end
end